# Generated by Django 5.1.1 on 2024-10-03 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_size', models.IntegerField(verbose_name='인원 수')),
                ('waiting_status', models.CharField(choices=[('waiting', '대기 중'), ('ready_to_confirm', '입장 확정 가능(관리자 호출)'), ('confirmed', '입장 확정'), ('arrived', '입장 완료'), ('canceled', '대기 취소'), ('time_over_canceled', '시간 초과로 취소')], default='waiting', max_length=20, verbose_name='대기 상태')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('ready_to_confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='입장 확정 가능 시작 시간')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='입장 확정 시간')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='대기 취소 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='대기 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='대기 업데이트 시간')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='booth.booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
