# Generated by Django 5.1.1 on 2025-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='waiting_num',
            field=models.IntegerField(default=0, verbose_name='대기 번호'),
            preserve_default=False,
        ),
    ]
