# Generated by Django 5.1.1 on 2024-10-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='waiting_status',
            field=models.CharField(choices=[('waiting', '대기 중'), ('ready_to_confirm', '입장 확정 가능(관리자 호출)'), ('confirmed', '입장 확정'), ('arrived', '입장 완료'), ('canceled', '대기 취소'), ('time_over_canceled', '시간 초과로 취소')], default='waiting', max_length=20, verbose_name='대기 상태'),
        ),
    ]
