# Generated by Django 5.1.1 on 2025-03-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting',
            old_name='party_size',
            new_name='person_num',
        ),
        migrations.RenameField(
            model_name='waiting',
            old_name='id',
            new_name='waiting_id',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='ready_to_confirm_at',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='waiting',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='대기 호출 시간'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='waiting_status',
            field=models.CharField(choices=[('waiting', '대기중'), ('canceled', '대기 취소'), ('entered', '입장 완료'), ('entering', '입장중'), ('not_waiting', '입장중 아님'), ('time_over', '대기시간 초과')], default='waiting', max_length=20, verbose_name='대기 상태'),
        ),
    ]
