# Generated by Django 5.1.1 on 2025-04-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0002_waiting_waiting_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='arrived_at',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='입장 시간'),
        ),
    ]
