# Generated by Django 5.1.1 on 2025-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0002_rename_party_size_waiting_person_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='arrived_at',
            field=models.DurationField(blank=True, null=True, verbose_name='입장 시간'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='waiting_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('canceled', 'canceled'), ('entered', 'entered'), ('entering', 'entering'), ('not_waiting', 'not_waiting'), ('time_over', 'time_over')], default='waiting', max_length=20, verbose_name='대기 상태'),
        ),
    ]
