# Generated by Django 5.1.1 on 2025-05-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0003_alter_waiting_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
