# Generated by Django 5.1.1 on 2025-04-13 00:57

import booth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('booth_id', models.AutoField(primary_key=True, serialize=False)),
                ('booth_name', models.CharField(max_length=100, verbose_name='부스명')),
                ('booth_description', models.TextField(verbose_name='부스 설명')),
                ('booth_location', models.CharField(max_length=255, verbose_name='부스 위치')),
                ('booth_start_time', models.DateTimeField(verbose_name='운영 시작 시간')),
                ('booth_end_time', models.DateTimeField(verbose_name='운영 마감 시간')),
                ('booth_notice', models.TextField(verbose_name='부스 공지')),
                ('booth_latitude', models.CharField(max_length=255, verbose_name='부스 위치 위도')),
                ('booth_longitude', models.CharField(max_length=255, verbose_name='부스 위치 경도')),
                ('operating_status', models.CharField(choices=[('not_started', 'not_started'), ('operating', 'operating'), ('finished', 'finished'), ('paused', 'paused')], max_length=100, verbose_name='부스 운영 상태')),
                ('current_watiting_num', models.IntegerField(verbose_name='최신 대기 번호')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fastival_name', models.CharField(max_length=100, verbose_name='행사명')),
            ],
        ),
        migrations.CreateModel(
            name='BoothImage',
            fields=[
                ('booth_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('booth_image', models.ImageField(blank=True, null=True, upload_to=booth.models.image_upload_path, verbose_name='사진')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_images', to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='BoothMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100, verbose_name='메뉴 이름')),
                ('menu_price', models.IntegerField(verbose_name='메뉴 가격')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_menus', to='booth.booth')),
            ],
        ),
    ]
