# Generated by Django 5.1.1 on 2024-09-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='is_operated',
            field=models.CharField(choices=[('operating', 'Operating'), ('not_started', 'Not Started'), ('finished', 'Finished')], max_length=100, verbose_name='운영 여부'),
        ),
    ]
