# Generated by Django 5.1.1 on 2025-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_rename_current_watiting_num_booth_current_waiting_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='is_restart',
            field=models.BooleanField(default=False, verbose_name='재시작 여부'),
        ),
    ]
