# Generated by Django 5.1.1 on 2024-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_alter_booth_is_operated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothmenu',
            name='price',
            field=models.IntegerField(verbose_name='가격'),
        ),
    ]
