# Generated by Django 5.1.1 on 2024-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_alter_boothmenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='is_operated',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('operating', 'Operating'), ('finished', 'Finished')], max_length=100, verbose_name='운영 여부'),
        ),
    ]
