# Generated by Django 5.1.1 on 2025-05-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_remove_booth_manager_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='관리자 연락처'),
        ),
    ]
