# Generated by Django 5.1.1 on 2025-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0006_booth_manager_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="GDG_id",
            field=models.IntegerField(null=True, verbose_name="GDG부스 id"),
        ),
        migrations.AddField(
            model_name="booth",
            name="is_GDGbooth",
            field=models.BooleanField(default=False, verbose_name="GDG부스 여부"),
        ),
    ]
