# Generated by Django 5.1.1 on 2025-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0007_booth_gdg_id_booth_is_gdgbooth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="GDG_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="GDG부스 id"),
        ),
    ]
