# Generated by Django 5.1.1 on 2025-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_alter_boothmenu_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothmenu',
            name='menu_name',
            field=models.TextField(verbose_name='메뉴 이름'),
        ),
    ]
