# Generated by Django 5.1.1 on 2025-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAuthenticate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(help_text='인증 받을 전화번호', max_length=20)),
                ('sms_code', models.CharField(help_text='문자인증 코드', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='인증 코드 발송 시각')),
            ],
        ),
    ]
