# Generated by Django 5.1.1 on 2025-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_smsauthenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsauthenticate',
            name='sms_code',
            field=models.TextField(help_text='문자인증 코드'),
        ),
    ]
