# Generated by Django 5.1.1 on 2025-04-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_smsauthenticate_sms_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsauthenticate',
            old_name='user_phone',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='login_id',
        ),
    ]
