# Generated by Django 5.1.1 on 2025-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_phone_smsauthenticate_login_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsauthenticate',
            old_name='login_id',
            new_name='user_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(help_text='used for authentication.', max_length=20, unique=True),
        ),
    ]
