# Generated by Django 5.1.1 on 2025-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_show_num',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='no_show_num',
            field=models.IntegerField(default=0),
        ),
    ]
