# Generated by Django 5.1.1 on 2025-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsauthenticate',
            name='sms_count',
            field=models.IntegerField(default=0, help_text='인증 코드 발송 횟수'),
        ),
    ]
