# Generated by Django 5.1.1 on 2025-04-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('ask_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_code', models.CharField(max_length=255, unique=True)),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='booth.booth')),
            ],
        ),
    ]
